import './legal.css'

type LegalPageProps={kind:'privacy'|'terms'}
const effectiveDate='19 September 2026'

function Mark(){return <a className="legal-mark" href="/" aria-label="SatQuery AI home"><svg viewBox="0 0 60 58" aria-hidden="true"><path fill="#ff9838" d="M5 26C10 4 37 20 53 4C53 25 23 13 5 26Z"/><path fill="#f5fcff" d="M4 39C12 16 40 33 54 17C53 38 22 26 4 39Z"/><path fill="#27bb87" d="M3 52C13 29 40 45 53 31C51 52 22 39 3 52Z"/></svg><span>SatQuery AI</span></a>}

function Privacy(){return <><header><p className="legal-kicker">Legal</p><h1>Privacy Policy</h1><p>This policy explains how SatQuery AI handles information when you sign in and use the application.</p><span>Effective {effectiveDate}</span></header><section><h2>Information we collect</h2><p>When you create an account with email and password or sign in with Google, our authentication provider, Supabase, processes your account credentials. We may receive and store basic account information such as your email address, display name, profile image, and authentication identifier.</p><p>When you use your workspace, we store information you choose to create, including your profile details, projects, and query history. Your browser also stores the session information needed to keep you signed in.</p></section><section><h2>Files and geospatial requests</h2><p>Files you upload for analysis are sent to our Vercel-hosted API for temporary processing. The application is designed to remove temporary files after the request completes and does not intentionally save uploaded datasets to your Supabase account.</p><p>Searches for satellite scenes may query the Element 84 Earth Search STAC service. Map views may load tiles from OpenStreetMap. Those providers may receive ordinary network information, such as your IP address, under their own policies.</p></section><section><h2>How we use information</h2><ul><li>To create and secure your account.</li><li>To provide a separate workspace, projects, and query history for each user.</li><li>To process the analysis requests you initiate.</li><li>To maintain, troubleshoot, and protect the service.</li></ul><p>We do not sell your personal information or use it for targeted advertising.</p></section><section><h2>Storage, access, and retention</h2><p>Account and workspace data is stored with Supabase. Row-level access rules are used so authenticated users can access their own records. Vercel, Supabase, Google, and other infrastructure providers may retain operational and security logs according to their own policies.</p><p>We retain your account data while your account is active or as needed to operate and protect the service. You may request access, correction, or deletion of your account data.</p></section><section><h2>Security and children</h2><p>We use reasonable technical safeguards, but no internet service can guarantee absolute security. SatQuery AI is not directed to children under 13, and we do not knowingly collect their personal information.</p></section><section><h2>Contact and changes</h2><p>For privacy questions or account-deletion requests, contact the SatQuery AI project owner using the support email shown on the Google sign-in consent screen. We may update this policy as the service changes; the effective date above will identify the current version.</p></section></>}

function Terms(){return <><header><p className="legal-kicker">Legal</p><h1>Terms of Service</h1><p>These terms govern your access to and use of the SatQuery AI prototype.</p><span>Effective {effectiveDate}</span></header><section><h2>Using SatQuery AI</h2><p>You may use SatQuery AI only in compliance with applicable laws and these terms. You are responsible for your account, for keeping your credentials secure, and for all activity performed through your account.</p><p>You must not misuse the service, attempt unauthorized access, disrupt its operation, upload malicious material, or use it to violate another person’s rights.</p></section><section><h2>Your content</h2><p>You retain ownership of files, project information, and other content you submit. You confirm that you have the right to use that content and grant us the limited permission needed to process it and provide the requested service.</p></section><section><h2>Prototype and geospatial outputs</h2><p>SatQuery AI is a prototype and its analyses, maps, comparisons, and generated materials may be incomplete, illustrative, or inaccurate. You must independently verify outputs before relying on them. Do not use the service as the sole basis for emergency response, public safety, legal, financial, environmental, or other high-impact decisions.</p></section><section><h2>Third-party services</h2><p>The service relies on third parties including Supabase, Google, Vercel, Element 84 Earth Search, and OpenStreetMap. Their services and content may be governed by separate terms and may change or become unavailable.</p></section><section><h2>Availability and warranties</h2><p>The service is provided “as is” and “as available,” without warranties of accuracy, reliability, availability, or fitness for a particular purpose. To the extent permitted by law, the project owner is not liable for indirect, incidental, or consequential losses arising from use of the service.</p></section><section><h2>Suspension, changes, and contact</h2><p>Access may be limited or suspended to protect users, comply with law, or prevent misuse. Features and these terms may change as the prototype develops. Continued use after an update means you accept the revised terms.</p><p>For questions, contact the SatQuery AI project owner using the support email shown on the Google sign-in consent screen.</p></section></>}

export default function LegalPage({kind}:LegalPageProps){return <div className="legal-page"><nav><Mark/><a href="/">Back to home</a></nav><main>{kind==='privacy'?<Privacy/>:<Terms/>}</main><footer><Mark/><div><a href="/privacy">Privacy Policy</a><a href="/terms">Terms of Service</a></div></footer></div>}
