import { useState } from 'react'
import { ArrowRight, Check, CloudUpload, FileText, Layers, MapPin, Radar, ShieldCheck } from 'lucide-react'
import './product-sections.css'

export default function ProductSections({enter}:{enter:()=>void}){
  const [split,setSplit]=useState(50)
  return <>
    <section className="sq-data-section sq-reveal"><div className="sq-data-heading"><span>Bring the right evidence</span><h2>Different sensors.<br/>A shared view of Earth.</h2><p>Use the imagery that fits the question. Acquisition dates, spatial resolution and source details belong alongside every observation.</p></div><div className="sq-source-grid"><article><div className="sq-source-visual optical"><span>Optical</span><div className="sq-spectrum"><i/><i/><i/><i/><i/></div></div><h3><Layers/>Sentinel-2</h3><p>Recognisable land features and multispectral bands for vegetation and surface-water indices.</p><small>Visible + near-infrared · date-based search</small></article><article><div className="sq-source-visual sar"><span>Radar</span><div className="sq-radar-lines"/></div><h3><Radar/>Sentinel-1</h3><p>Radar observations provide complementary context when clouds obstruct an optical scene.</p><small>SAR workflow · planned model integration</small></article><article><div className="sq-source-visual upload"><div className="sq-file-stack"><FileText/><span>district_scene.tif</span><small>4 bands · CRS retained</small></div></div><h3><CloudUpload/>Your GeoTIFFs</h3><p>Bring a local raster into the workspace and inspect its dimensions, bands and georeferencing.</p><small>Local inspection · FastAPI tools</small></article></div><div className="sq-indian-source"><MapPin/><p><b>Designed with Indian workflows in mind.</b> Bhoonidhi is a planned source connector. INSAT weather context is separate from detailed land-surface analysis.</p></div></section>
    <section className="sq-comparison-section sq-reveal"><div className="sq-comparison-visual"><div className="sq-comparison-base"/><div className="sq-comparison-result" style={{clipPath:`inset(0 ${100-split}% 0 0)`}}><svg viewBox="0 0 500 400" preserveAspectRatio="none"><path d="M240 0L320 35 280 87 355 115 303 174 363 210 348 244 427 282 410 340 483 400H372L319 341 320 294 252 251 271 209 218 165 252 114 202 73Z"/></svg></div><span className="sq-compare-badge">With selected-region overlay</span><span className="sq-compare-badge right">Original illustration</span><div className="sq-comparison-divider" style={{left:`${split}%`}}><b>‹ ›</b></div><input aria-label="Reveal the selected region" type="range" min="5" max="95" value={split} onChange={e=>setSplit(Number(e.target.value))}/><small>Drag to compare · illustrative region overlay</small></div><div className="sq-comparison-copy"><span>Explore the evidence yourself</span><h2>Make the question<br/>visually precise.</h2><p>“What is this area?” becomes a useful question when the selected region travels with it. Keep the scene visible while you inspect the answer.</p><ul><li><Check/>Identify the area before running analysis</li><li><Check/>Compare the overlay with the source image</li><li><Check/>Keep human review in the workflow</li></ul><button onClick={enter}>Explore region selection <ArrowRight/></button></div></section>
    <section className="sq-method-section sq-reveal"><div><span>A reviewable result</span><h2>Know what supports<br/>the answer.</h2><p>A useful response includes more than a paragraph. SatQuery’s interface brings the source, tool result and review context together.</p></div><div className="sq-method-columns"><article><span>01</span><h3>Source imagery</h3><p>Know which scene and acquisition date were used, with the original image available for comparison.</p></article><article><span>02</span><h3>Measured evidence</h3><p>Inspect deterministic GIS outputs such as raster metadata, water-index masks and area calculations.</p></article><article><span>03</span><h3>Human review</h3><p>Review the selected region and limitations before using an observation for field decisions.</p></article></div><div className="sq-prototype-note"><ShieldCheck/><p><b>Where the prototype stands</b> Interactive UI and local GIS calculations are implemented. The adapted remote-sensing model and optical–SAR reasoning remain integration work; prepared narratives are labelled in the workspace.</p></div></section>
    <section className="sq-faq-section sq-reveal"><div><span>Before you begin</span><h2>A few useful answers.</h2><p>What the prototype does today, and what comes next.</p></div><div>{[
      ['Is this live satellite video?','No. Satellite imagery consists of individual acquisitions. A catalogue can return recent and historical scenes; availability depends on the sensor, coverage, clouds and processing delay.'],
      ['Can I upload my own imagery?','The local prototype accepts GeoTIFF files for raster inspection. The API also supports a two-raster NDWI water-change calculation with explicit green and near-infrared band selection.'],
      ['Are the answers generated by a trained model?','The current narrative is prepared demonstration output. GIS values can be computed locally from the bundled synthetic GeoTIFFs. An adapted remote-sensing model has not yet been connected.'],
      ['Who is the workspace designed for?','Disaster-management officers, district planners and remote-sensing analysts who need to examine a place, compare observations and review evidence.'],
      ['What will be needed for an operational pilot?','Validated scene pairs, task-specific evaluation, model integration, secure deployment and review by domain experts. The current prototype is for demonstration and testing.']
    ].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
  </>
}
