import { chromium } from 'playwright'
import { mkdir } from 'node:fs/promises'
await mkdir('output/studio', { recursive:true })
const browser = await chromium.launch({headless:true,channel:'msedge'})
const page = await browser.newPage({viewport:{width:1366,height:850}})
const errors=[]
page.on('pageerror', error=>errors.push(error.message))
try {
  await page.goto('http://127.0.0.1:5173/',{waitUntil:'networkidle'})
  await page.screenshot({path:'output/studio/landing.png'})
  await page.getByRole('button',{name:'Open workspace',exact:true}).first().click()
  await page.getByRole('button',{name:/Inputs ·/}).click()
  await page.getByRole('button',{name:/Try real Sentinel-2 data/}).click()
  await page.locator('.studio-raster').waitFor()
  await page.screenshot({path:'output/studio/workspace.png'})
  await page.getByLabel('Ask about your selected images').fill('What changed in water extent between these two dates?')
  await page.getByRole('button',{name:'Analyse',exact:true}).click()
  await page.locator('.studio-answer').waitFor({timeout:60000})
  console.log('MEASURED:',await page.locator('.studio-answer-copy').innerText())
  await page.screenshot({path:'output/studio/measured.png'})
  await page.getByRole('button',{name:/Inputs ·/}).click()
  await page.locator('.studio-asset-image').nth(1).click()
  await page.keyboard.press('Escape')
  await page.getByLabel('Ask about your selected images').fill('Describe the land-cover and major objects visible in this image.')
  await page.getByRole('button',{name:'Analyse',exact:true}).click()
  await page.locator('.studio-answer').waitFor({timeout:90000})
  console.log('VISION:',(await page.locator('.studio-answer-copy').innerText()).slice(0,350))
  await page.screenshot({path:'output/studio/vision.png'})
  await page.getByLabel('Ask about your selected images').fill('Highlight the water body in this image.')
  await page.getByRole('button',{name:'Analyse',exact:true}).click()
  await page.locator('.studio-answer').nth(1).waitFor({timeout:30000})
  await page.screenshot({path:'output/studio/grounding.png'})
  await page.getByLabel('Ask about your selected images').fill('What changed between these two dates?')
  await page.getByRole('button',{name:'Analyse',exact:true}).click()
  await page.getByRole('alert').waitFor()
  console.log('VALIDATION:',await page.getByRole('alert').innerText())
  await page.getByRole('button',{name:/Inputs ·/}).click()
  await page.getByRole('button',{name:'Optical + SAR',exact:true}).click()
  await page.keyboard.press('Escape')
  await page.getByLabel('Ask about your selected images').fill('Use the optical and SAR images together to identify water-covered and built-up regions. Explain the complementary evidence.')
  await page.getByRole('button',{name:'Analyse',exact:true}).click()
  await page.locator('.studio-answer').waitFor({timeout:90000})
  console.log('RADAR:',(await page.locator('.studio-answer-copy').innerText()).slice(0,350))
  await page.screenshot({path:'output/studio/radar.png'})
  const downloading = page.waitForEvent('download')
  await page.getByRole('button',{name:'Download evidence report',exact:true}).click()
  await (await downloading).saveAs('output/studio/evidence-report.html')
  await page.keyboard.press('Escape')
  await page.getByRole('button',{name:'How it works',exact:true}).click()
  await page.screenshot({path:'output/studio/architecture.png',animations:'disabled'})
  await page.getByRole('button',{name:'Close architecture',exact:true}).click()
  for (const size of [{width:1366,height:768},{width:1920,height:1080},{width:1024,height:768}]) {
    await page.setViewportSize(size)
    console.log('LAYOUT',size,await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth})))
    await page.screenshot({path:`output/studio/layout-${size.width}.png`})
  }
  console.log('BROWSER ERRORS:',errors)
  if(errors.length) process.exitCode=1
} finally {await browser.close()}
