import { chromium } from 'playwright'
import { mkdir } from 'node:fs/promises'
await mkdir('output/studio',{recursive:true})
const browser=await chromium.launch({headless:true,channel:'msedge'})
const page=await browser.newPage({viewport:{width:1366,height:850}})
try {
  await page.goto('http://127.0.0.1:5173/')
  await page.getByRole('button',{name:'Open workspace',exact:true}).first().click()
  await page.getByRole('button',{name:'Start exploring',exact:true}).waitFor()
  await page.screenshot({path:'output/studio/introduction.png',animations:'disabled'})
  await page.getByRole('button',{name:/02\s*Locate/}).click()
  await page.getByRole('button',{name:'Start exploring',exact:true}).click()
  await page.getByRole('button',{name:/Inputs ·/}).click()
  await page.getByRole('button',{name:'Discover imagery',exact:true}).click()
  await page.getByRole('button',{name:/Explore Upper Lake collection/}).click()
  await page.getByLabel('Find coordinates').fill('23.26, 77.30')
  await page.getByRole('button',{name:'Go to location'}).click()
  await page.waitForTimeout(800)
  await page.getByRole('button',{name:'Search this map area'}).click()
  await page.getByRole('button',{name:'Select Upper Lake · landscape view 2021-05-06',exact:true}).click()
  await page.screenshot({path:'output/studio/discovery-real.png'})
  await page.getByRole('button',{name:'Continue',exact:true}).click()
  await page.locator('.studio-raster').waitFor()
  await page.getByRole('button',{name:'False colour',exact:true}).click()
  await page.getByText('False colour: NIR / red / green',{exact:true}).waitFor()
  await page.screenshot({path:'output/studio/false-colour.png'})
  await page.getByRole('button',{name:'NDWI',exact:true}).click()
  await page.getByText(/NDWI =/).waitFor()
  await page.screenshot({path:'output/studio/ndwi.png'})
  await page.getByRole('button',{name:'How it works',exact:true}).click()
  await page.screenshot({path:'output/studio/architecture.png',animations:'disabled'})
  console.log('PASS: tutorial, real collection search/attachment, false colour, NDWI, architecture')
} finally {await browser.close()}
