import { useEffect, useState, type FormEvent } from 'react'
import { Check, Chrome, Database, LogOut, Save, User, X } from 'lucide-react'
import { useAccount } from './AccountContext'

export default function AccountDialog({ open, onClose }: { open: boolean; onClose: () => void }) {
  const account = useAccount(); const [mode, setMode] = useState<'login' | 'signup'>('login')
  const [email, setEmail] = useState(''), [password, setPassword] = useState(''), [fullName, setFullName] = useState(''), [organization, setOrganization] = useState(''), [status, setStatus] = useState(''), [busy, setBusy] = useState(false)
  useEffect(() => { setFullName(account.profile?.full_name ?? account.user?.user_metadata.full_name ?? ''); setOrganization(account.profile?.organization ?? '') }, [account.profile, account.user])
  if (!open) return null
  const run = async (work: () => Promise<void>, success: string) => { setBusy(true); setStatus(''); try { await work(); setStatus(success) } catch (error) { setStatus(error instanceof Error ? error.message : 'Something went wrong.') } finally { setBusy(false) } }
  const submitAuth = (event: FormEvent) => { event.preventDefault(); void run(() => mode === 'login' ? account.signInWithPassword(email, password) : account.signUpWithPassword(email, password, fullName), mode === 'login' ? 'Signed in. Loading your workspace…' : 'Check your inbox to confirm your account, then sign in.') }
  const submitProfile = (event: FormEvent) => { event.preventDefault(); void run(() => account.saveProfile(fullName, organization), 'Profile saved.') }
  return <div className="account-backdrop" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) onClose() }}><section className="account-dialog" role="dialog" aria-modal="true" aria-labelledby="account-title"><button className="account-close" onClick={onClose} aria-label="Close account panel"><X /></button><div className="account-heading"><span><Database /></span><div><small>YOUR PRIVATE WORKSPACE</small><h2 id="account-title">{account.user ? 'Account settings' : mode === 'login' ? 'Welcome back' : 'Create your account'}</h2><p>{account.user ? 'Your projects and query history are private to this account.' : 'Use your email and password, or continue with Google.'}</p></div></div>
  {!account.configured ? <div className="account-setup"><Database /><div><b>Connect your Supabase project</b><p>Add the project URL and publishable key to <code>.env.local</code>, then run the workspace migration.</p></div></div>
  : account.loading ? <div className="account-loading">Checking your session…</div>
  : account.user ? <form className="account-form" onSubmit={submitProfile}><div className="account-user"><span><User /></span><div><b>{account.profile?.full_name || account.user.email}</b><small>{account.user.email}</small></div><i><Check /> Signed in</i></div><label>Full name<input value={fullName} onChange={event => setFullName(event.target.value)} maxLength={100} placeholder="Your name" /></label><label>Organisation<input value={organization} onChange={event => setOrganization(event.target.value)} maxLength={160} placeholder="Department or organisation" /></label>{status && <p className="account-status">{status}</p>}<div className="account-actions"><button type="button" className="secondary-button" onClick={() => void account.signOut()}><LogOut />Sign out</button><button className="primary-button" disabled={busy}><Save />{busy ? 'Saving…' : 'Save profile'}</button></div></form>
  : <><div className="account-tabs"><button className={mode === 'login' ? 'active' : ''} onClick={() => setMode('login')}>Log in</button><button className={mode === 'signup' ? 'active' : ''} onClick={() => setMode('signup')}>Sign up</button></div><form className="account-form" onSubmit={submitAuth}>{mode === 'signup' && <label>Full name<input required value={fullName} onChange={event => setFullName(event.target.value)} maxLength={100} placeholder="Your name" /></label>}<label>Email address<input type="email" required value={email} onChange={event => setEmail(event.target.value)} placeholder="you@example.com" /></label><label>Password<input type="password" required minLength={6} value={password} onChange={event => setPassword(event.target.value)} placeholder="At least 6 characters" /></label>{status && <p className="account-status">{status}</p>}<button className="primary-button account-submit" disabled={busy}>{busy ? 'Please wait…' : mode === 'login' ? 'Log in' : 'Create account'}</button></form><div className="account-divider"><span>or</span></div><button className="google-button" disabled={busy} onClick={() => void run(account.signInWithGoogle, 'Redirecting to Google…')}><Chrome />Continue with Google</button><p className="account-note">Google sign-in must be enabled in your Supabase Authentication providers first.</p></>}</section></div>
}
