import { useEffect, useMemo, useState, type CSSProperties } from 'react'
import { Activity, ArrowLeft, ArrowRight, Blend, Bot, Box, Brush, Check, ChevronDown, Clock3, Cloud, Database, Eraser, Eye, FileText, HelpCircle, History, Image as ImageIcon, Layers, LayoutDashboard, LocateFixed, Map, MapPin, Moon, MoreHorizontal, PanelLeft, Plus, Radar, RefreshCw, Search, Send, Settings, SlidersHorizontal, Sparkles, SquareDashedMousePointer, Sun, Upload, User, WandSparkles, Zap } from 'lucide-react'
import './analysis-workspace.css'

type Section = 'dashboard' | 'copilot' | 'change' | 'fusion' | 'geo' | 'reports' | 'settings'
type Theme = 'dark' | 'light'
type Asset = { id: string; name: string; meta: string; kind: 'optical' | 'sar' | 'raster' }
const assets: Asset[] = [
  { id: 'before', name: 'Supaul · before', meta: '12 Aug 2023 · Sentinel-2 L2A', kind: 'optical' },
  { id: 'after', name: 'Supaul · after', meta: '28 Aug 2023 · Sentinel-2 L2A', kind: 'optical' },
  { id: 'sar', name: 'Supaul · radar', meta: '16 Aug 2023 · Sentinel-1 GRD', kind: 'sar' },
]
const navItems = [
  ['dashboard', 'Dashboard', 'Overview & recent work', LayoutDashboard], ['copilot', 'SatQuery Copilot', 'Ask one image', Bot],
  ['change', 'Change Intelligence', 'Compare dates', Activity], ['fusion', 'Multimodal Fusion', 'Optical + SAR', Blend],
  ['geo', 'Geo Intelligence', 'Measure & inspect', Map], ['reports', 'Intelligence Reports', 'Review & export', FileText],
] as const
const titles: Record<Section, [string, string]> = {
  dashboard: ['Mission overview', 'Your imagery, analyses and evidence in one place'], copilot: ['SatQuery Copilot', 'Ground questions in one image or selected region'],
  change: ['Change Intelligence', 'Align two observations and inspect meaningful change'], fusion: ['Multimodal Fusion', 'Cross-check optical evidence with radar observations'],
  geo: ['Geo Intelligence', 'Inspect geospatial data and run deterministic measurements'], reports: ['Intelligence Reports', 'Turn completed analyses into reviewable briefs'],
  settings: ['Settings', 'Appearance, map defaults and workspace preferences'],
}
function Mark(){return <svg className="sq-mark" viewBox="0 0 60 58" aria-hidden="true"><path fill="#f89a38" d="M5 26C10 4 37 20 53 4C53 25 23 13 5 26Z"/><path fill="currentColor" d="M4 39C12 16 40 33 54 17C53 38 22 26 4 39Z"/><path fill="#35b98b" d="M3 52C13 29 40 45 53 31C51 52 22 39 3 52Z"/></svg>}
function Status({tone='ready',children}:{tone?:'ready'|'working'|'draft';children:React.ReactNode}){return <span className={`status-badge ${tone}`}><i/>{children}</span>}
function AppRail({current,setCurrent,home}:{current:Section;setCurrent:(s:Section)=>void;home:()=>void}){return <aside className="app-rail">
  <button className="rail-brand" onClick={home}><Mark/><span><b>SatQuery</b> AI</span></button><nav>{navItems.map(([id,label,hint,Icon])=><button key={id} className={current===id?'active':''} onClick={()=>setCurrent(id)} title={label}><Icon/><span><b>{label}</b><small>{hint}</small></span></button>)}</nav>
  <div className="rail-foot"><button className={current==='settings'?'active':''} onClick={()=>setCurrent('settings')}><Settings/><span><b>Settings</b><small>Preferences & layers</small></span></button><button className="profile-row"><span className="avatar">DK</span><span><b>Devansh Kumar</b><small>Prototype workspace</small></span><MoreHorizontal/></button></div>
</aside>}
function Dashboard({open}:{open:(s:Section)=>void}){return <div className="dashboard page-scroll">
  <section className="welcome-strip"><div><span className="eyebrow"><Sparkles/> EARTH OBSERVATION WORKSPACE</span><h2>Good evening, Devansh.</h2><p>Continue a prepared investigation or start with imagery from your computer.</p></div><button className="primary" onClick={()=>open('copilot')}><Plus/> New investigation</button></section>
  <section className="metric-grid">{[[Database,'Saved assets','08','3 optical · 2 radar · 3 rasters'],[Activity,'Analysis runs','04','1 prepared demo · 3 local drafts'],[MapPin,'Saved areas','03','Supaul · Dhemaji · Bhopal'],[FileText,'Reports','02','Both ready for review']].map(([Icon,label,value,note])=><article key={label as string}><span><Icon/>{label as string}</span><strong>{value as string}</strong><small>{note as string}</small></article>)}</section>
  <div className="dashboard-grid"><section className="surface recent-work"><div className="section-head"><div><span className="eyebrow">RECENT WORK</span><h3>Investigations</h3></div><button>View all <ArrowRight/></button></div>
    <button className="project-row" onClick={()=>open('change')}><span className="project-thumb before"/><span><b>Flood assessment · Supaul</b><small>Change Intelligence · 2 optical scenes</small></span><Status>Prepared</Status><span className="row-time">12 min ago</span><ArrowRight/></button>
    <button className="project-row" onClick={()=>open('fusion')}><span className="project-icon"><Radar/></span><span><b>Monsoon evidence cross-check</b><small>Multimodal Fusion · Optical + SAR</small></span><Status tone="draft">Draft</Status><span className="row-time">Yesterday</span><ArrowRight/></button>
    <button className="project-row" onClick={()=>open('geo')}><span className="project-icon"><Map/></span><span><b>Dhemaji raster inspection</b><small>Geo Intelligence · GeoTIFF</small></span><Status>Complete</Status><span className="row-time">04 Sep</span><ArrowRight/></button>
  </section><section className="surface activity-panel"><div className="section-head"><div><span className="eyebrow">ACTIVITY</span><h3>Current status</h3></div><button><RefreshCw/></button></div><div className="run-item"><span className="run-icon working"><Activity/></span><div><b>Supaul scene alignment</b><small>Prepared inputs validated</small><div className="progress"><i style={{width:'78%'}}/></div></div><Status tone="working">Processing</Status></div><div className="run-item"><span className="run-icon"><Check/></span><div><b>GeoTIFF area calculation</b><small>Deterministic result stored</small></div><Status>Complete</Status></div><div className="activity-note"><Cloud/><span><b>Local prototype session</b><small>Files remain in this browser session.</small></span></div></section></div>
  <section className="tool-section"><div className="section-head"><div><span className="eyebrow">QUICK START</span><h3>Choose the job, not the technology</h3></div></div><div className="tool-grid">{navItems.slice(1,5).map(([id,label,hint,Icon],i)=><button key={id} onClick={()=>open(id)}><span className="tool-number">0{i+1}</span><Icon/><b>{label}</b><small>{hint}. Open the purpose-built workspace.</small><ArrowRight/></button>)}</div></section>
</div>}
function UploadTile({label,onFile}:{label:string;onFile:(file:File)=>void}){return <label className="upload-tile"><Upload/><span><b>{label}</b><small>PNG, JPG or GeoTIFF · up to 500 MB</small></span><input type="file" accept="image/*,.tif,.tiff" onChange={e=>e.target.files?.[0]&&onFile(e.target.files[0])}/></label>}
function AssetLibrary({mode,onFile,active,setActive}:{mode:Section;onFile:(f:File)=>void;active:string;setActive:(s:string)=>void}){const list=mode==='fusion'?assets:mode==='change'?assets.slice(0,2):assets.slice(1,2);return <aside className="asset-panel"><div className="panel-title"><div><span className="eyebrow">INPUTS</span><h3>{mode==='change'?'Scene pair':mode==='fusion'?'Sensor inputs':mode==='geo'?'Raster assets':'Imagery'}</h3></div><button><Search/></button></div><div className="source-switch"><button className="active"><History/> Recent</button><button><Cloud/> Catalogue</button></div><UploadTile label={mode==='change'?'Add comparison image':mode==='fusion'?'Add sensor image':mode==='geo'?'Add geospatial raster':'Add your image'} onFile={onFile}/><div className="asset-list-label"><span>Prepared demo assets</span><small>Illustrative</small></div><div className="asset-list">{list.map((a,i)=><button key={a.id} className={active===a.id?'selected':''} onClick={()=>setActive(a.id)}><span className={`asset-thumb ${a.id}`}/><span><b>{mode==='change'?(i?'After':'Before'):a.name}</b><small>{a.meta}</small><em>{a.kind}</em></span>{active===a.id&&<Check/>}</button>)}</div><p className="prepared-note"><HelpCircle/> Prepared assets demonstrate interaction only. They are not validated observations.</p></aside>}
function ImageCanvas({mode,url,maskTool}:{mode:Section;url?:string;maskTool:string}){const [zoom,setZoom]=useState(1),[split,setSplit]=useState(54),[showMask,setShowMask]=useState(mode!=='change'),[compare,setCompare]=useState(mode==='change');const style=url?{'--canvas-image':`url("${url}")`} as CSSProperties:undefined;return <section className="image-canvas" style={style}><div className="canvas-topbar"><div><MapPin/><span><b>Supaul, Bihar</b><small>26.1267° N, 86.6050° E</small></span></div><div className="canvas-controls"><button><Search/></button><button><Layers/> Layers</button><button><LocateFixed/></button></div></div><div className="canvas-image base"/>{mode==='change'&&compare&&<div className="canvas-image after" style={{clipPath:`inset(0 0 0 ${split}%)`}}/>}{mode==='fusion'&&<div className="sar-overlay"/>}{(mode==='copilot'||mode==='geo')&&showMask&&<svg className="selection-mask" viewBox="0 0 1000 800" preserveAspectRatio="none"><path d="M430 260L500 215 580 245 620 325 600 405 665 472 612 548 515 565 450 505 392 428 405 338Z"/></svg>}
  {mode==='change'&&compare&&<div className="compare-line" style={{left:`${split}%`}}><button onPointerDown={e=>{const root=e.currentTarget.closest('.image-canvas') as HTMLElement;const move=(x:PointerEvent)=>{const b=root.getBoundingClientRect();setSplit(Math.max(5,Math.min(95,(x.clientX-b.left)/b.width*100)))};const done=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',done)};window.addEventListener('pointermove',move);window.addEventListener('pointerup',done)}}><ArrowLeft/><ArrowRight/></button></div>}
  <div className="scene-labels"><span>{mode==='change'?'12 Aug 2023 · Before':url?'Uploaded image':'Prepared optical scene'}</span>{mode==='change'&&<span>28 Aug 2023 · After</span>}</div><div className="canvas-toolbox">{(mode==='copilot'||mode==='geo')&&<><button className={maskTool==='point'?'active':''}><MapPin/></button><button className={maskTool==='box'?'active':''}><Box/></button><button className={maskTool==='brush'?'active':''}><Brush/></button><button><Eraser/></button></>}{mode==='change'&&<><button className={compare?'active':''} onClick={()=>setCompare(true)}><PanelLeft/></button><button onClick={()=>setCompare(false)}><Eye/></button></>}<span/><button onClick={()=>setZoom(v=>Math.min(2.5,v+.25))}><Plus/></button><button onClick={()=>setZoom(v=>Math.max(1,v-.25))}>−</button></div><div className="canvas-foot"><span><b>N</b> ↑</span><span>Prepared imagery · {zoom.toFixed(2)}×</span><span>10 m / px</span></div>
  {mode==='copilot'&&<div className="selection-tag"><SquareDashedMousePointer/><span><b>Selected river corridor</b><small>27.1 km² · user-defined</small></span><button onClick={()=>setShowMask(v=>!v)}>{showMask?'Hide':'Show'}</button></div>}{mode==='fusion'&&<div className="fusion-legend"><span><i className="optical-dot"/> Optical surface detail</span><span><i className="sar-dot"/> SAR response overlay</span><small>Illustrative blend · not a fused model output</small></div>}</section>}
function EvidencePanel({mode}:{mode:Section}){const [q,setQ]=useState(''),[messages,setMessages]=useState<string[]>([]),[open,setOpen]=useState(true);const options:Record<string,string[]>={copilot:['What is inside the selected region?','The selected corridor contains a braided river channel, exposed sand bars and adjacent agricultural parcels.','27.1','km² selected'],change:['What changed between these dates?','Use the swipe to inspect the prepared pair. Quantified change appears only after aligned raster analysis is run.','2','scenes ready'],fusion:['Do optical and SAR agree?','Both prepared inputs cover the same area. Sensor findings remain separate until the fusion model is connected.','2','sensors linked'],geo:['What can be measured here?','Upload a GeoTIFF to inspect its CRS, bands and dimensions, then calculate area or index statistics deterministically.','4','GIS tools ready']};const copy=options[mode]||['','','',''];const submit=()=>{if(q.trim()){setMessages(v=>[...v,q.trim()]);setQ('')}};return <aside className="evidence-panel"><div className="evidence-brand"><Mark/><span><b>SatQuery</b><small>Evidence workspace</small></span><Status tone="draft">Prepared</Status></div><div className="evidence-scroll"><span className="eyebrow">YOUR QUESTION</span><h3>{messages.at(-1)||copy[0]}</h3><div className="answer-block"><span className="answer-label"><WandSparkles/> PREPARED DEMONSTRATION</span><p>{copy[1]}</p><div><strong>{copy[2]}</strong><small>{copy[3]}</small></div></div><div className="evidence-chips"><button><Layers/> Selected region</button><button><ImageIcon/> Source imagery</button></div><button className="trace-head" onClick={()=>setOpen(v=>!v)}><span><Activity/> Analysis trace</span><span>3 / 4 <ChevronDown className={open?'':'closed'}/></span></button>{open&&<div className="trace-list">{[['Input accepted','Metadata attached to this run'],['Region grounded','User selection preserved'],['Evidence prepared','Prototype narrative only']].map(([a,b])=><p key={a}><Check/><span><b>{a}</b><small>{b}</small></span></p>)}<p className="pending"><Clock3/><span><b>Model inference</b><small>Not connected in this build</small></span></p></div>}</div><div className="composer"><div><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&submit()} placeholder="Ask about this evidence"/><button onClick={submit}><Send/></button></div><small>Prepared answers are labelled until a model is connected.</small></div></aside>}
function Workbench({mode}:{mode:Section}){const [active,setActive]=useState(mode==='change'?'after':mode==='fusion'?'sar':'after'),[url,setUrl]=useState<string>(),[tool,setTool]=useState('box');useEffect(()=>()=>{if(url)URL.revokeObjectURL(url)},[url]);const onFile=(f:File)=>setUrl(old=>{if(old)URL.revokeObjectURL(old);setActive('upload');return URL.createObjectURL(f)});return <div className="workbench"><AssetLibrary mode={mode} onFile={onFile} active={active} setActive={setActive}/><div className="canvas-column"><div className="mode-toolbar"><div><span className="eyebrow">ACTIVE WORKFLOW</span><b>{titles[mode][0]}</b></div>{(mode==='copilot'||mode==='geo')&&<div className="mask-tools"><span>Selection</span>{[['point',MapPin],['box',Box],['brush',Brush]].map(([id,Icon])=><button key={id as string} onClick={()=>setTool(id as string)} className={tool===id?'active':''}><Icon/><span>{id as string}</span></button>)}</div>}<button className="quiet"><SlidersHorizontal/> View</button></div><ImageCanvas mode={mode} url={url} maskTool={tool}/></div><EvidencePanel mode={mode}/></div>}
function Reports({open}:{open:(s:Section)=>void}){return <div className="reports page-scroll"><div className="reports-toolbar"><div className="segmented"><button className="active">All reports</button><button>Ready</button><button>Drafts</button></div><button className="primary"><Plus/> Create report</button></div><section className="surface report-table"><div className="table-head"><span>Report</span><span>Workflow</span><span>Status</span><span>Updated</span><span/></div>{[['Supaul flood evidence brief','Change Intelligence','Ready','12 min ago','change'],['Monsoon sensor cross-check','Multimodal Fusion','Draft','Yesterday','fusion'],['Dhemaji raster inspection','Geo Intelligence','Ready','04 Sep','geo']].map(([name,flow,status,time,target])=><button key={name} onClick={()=>open(target as Section)}><span><FileText/><span><b>{name}</b><small>Prepared prototype document</small></span></span><span>{flow}</span><Status tone={status==='Draft'?'draft':'ready'}>{status}</Status><span>{time}</span><ArrowRight/></button>)}</section></div>}
function SettingsPage({theme,setTheme}:{theme:Theme;setTheme:(t:Theme)=>void}){const [labels,setLabels]=useState(true),[roads,setRoads]=useState(false),[save,setSave]=useState(true);return <div className="settings-page page-scroll"><section className="settings-section"><span className="eyebrow">APPEARANCE</span><h3>Interface theme</h3><p>Choose the workspace appearance. Your preference is saved locally.</p><div className="theme-grid">{([['dark',Moon,'Dark','Low-glare imagery review'],['light',Sun,'Light','Bright office environments']] as const).map(([id,Icon,name,note])=><button key={id} className={theme===id?'selected':''} onClick={()=>setTheme(id)}><span className={`theme-preview ${id}`}><i/><i/><i/></span><span><Icon/><b>{name}</b><small>{note}</small></span>{theme===id&&<Check/>}</button>)}</div></section><section className="settings-section"><span className="eyebrow">MAP DEFAULTS</span><h3>Workspace layers</h3><p>Set which contextual layers appear when a georeferenced asset is opened.</p><label className="setting-row"><span><Map/><span><b>Place labels</b><small>Districts, towns and geographic names</small></span></span><input type="checkbox" checked={labels} onChange={e=>setLabels(e.target.checked)}/></label><label className="setting-row"><span><Layers/><span><b>Roads and settlements</b><small>Additional reference context</small></span></span><input type="checkbox" checked={roads} onChange={e=>setRoads(e.target.checked)}/></label></section><section className="settings-section"><span className="eyebrow">SESSION</span><h3>Local workspace</h3><label className="setting-row"><span><Cloud/><span><b>Auto-save drafts</b><small>Keep prototype state in this browser</small></span></span><input type="checkbox" checked={save} onChange={e=>setSave(e.target.checked)}/></label></section></div>}
export default function AnalysisWorkspace({home}:{home:()=>void}){const [section,setSection]=useState<Section>('dashboard'),[theme,setTheme]=useState<Theme>(()=>(localStorage.getItem('satquery-theme') as Theme)||'dark');useEffect(()=>localStorage.setItem('satquery-theme',theme),[theme]);const [title,subtitle]=titles[section];const content=useMemo(()=>section==='dashboard'?<Dashboard open={setSection}/>:section==='reports'?<Reports open={setSection}/>:section==='settings'?<SettingsPage theme={theme} setTheme={setTheme}/>:<Workbench key={section} mode={section}/>,[section,theme]);return <main className="product-shell" data-theme={theme}><AppRail current={section} setCurrent={setSection} home={home}/><header className="product-header"><div><h1>{title}</h1><p>{subtitle}</p></div><div className="header-actions"><button><Search/></button><button><Zap/></button><span className="session"><Cloud/> Local session</span><button className="user-button"><User/><ChevronDown/></button></div></header><div className="product-content">{content}</div></main>}
