import { useEffect, useRef, useState, type CSSProperties, type PointerEvent as ReactPointerEvent } from 'react'
import { ArrowLeft, ArrowRight, Check, ChevronDown, ChevronsLeft, ChevronsRight, Clock3, Cloud, Download, FileText, HelpCircle, Home, Image, Layers, LocateFixed, MapPin, MessageSquare, Minus, PanelLeftClose, PanelRightClose, Paperclip, Plus, Search, Send, SquareDashedMousePointer, Upload, X } from 'lucide-react'
import './analysis-workspace.css'

function Mark(){return <svg className="aw-mark" viewBox="0 0 60 58" aria-hidden="true"><path fill="#ff9838" d="M5 26C10 4 37 20 53 4C53 25 23 13 5 26Z"/><path fill="#f5fcff" d="M4 39C12 16 40 33 54 17C53 38 22 26 4 39Z"/><path fill="#27bb87" d="M3 52C13 29 40 45 53 31C51 52 22 39 3 52Z"/></svg>}
type Scene={id:string;title:string;date:string;kind:string;cloud:number|null}
const scenes:Scene[]=[{id:'before',title:'Before',date:'12 Aug 2023',kind:'Optical',cloud:12},{id:'after',title:'After',date:'28 Aug 2023',kind:'Optical',cloud:28},{id:'sar',title:'Supporting radar',date:'16 Aug 2023',kind:'SAR',cloud:null}]
type Calculation={expandedAreaHa:number;changePercent:number;summary:string;trace:{label:string;detail:string}[]}
const clamp=(n:number,min:number,max:number)=>Math.min(max,Math.max(min,n))

export default function AnalysisWorkspace({home}:{home:()=>void}){
  const [rail,setRail]=useState(false),[left,setLeft]=useState(true),[right,setRight]=useState(true)
  const [leftWidth,setLeftWidth]=useState(230),[rightWidth,setRightWidth]=useState(365)
  const [imagery,setImagery]=useState(false),[tab,setTab]=useState('catalog'),[welcome,setWelcome]=useState(true),[task,setTask]=useState(2)
  const [chosen,setChosen]=useState(['before','after']),[draft,setDraft]=useState(['before','after']),[active,setActive]=useState('after')
  const [split,setSplit]=useState(43),[zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0}),[mask,setMask]=useState(true),[layers,setLayers]=useState(false),[selected,setSelected]=useState(true)
  const [region,setRegion]=useState({x:28,y:24,w:42,h:49}),[question,setQuestion]=useState(''),[asked,setAsked]=useState('Where did possible floodwater expand?')
  const [busy,setBusy]=useState(false),[calculation,setCalculation]=useState<Calculation|null>(null),[notice,setNotice]=useState('')
  const [place,setPlace]=useState('Supaul, Bihar, India'),[from,setFrom]=useState('2023-08-01'),[to,setTo]=useState('2023-08-31'),[cloud,setCloud]=useState(30),[optical,setOptical]=useState(true),[sar,setSar]=useState(true)
  const [uploadInfo,setUploadInfo]=useState(''),[searchInfo,setSearchInfo]=useState('Prepared catalogue · illustrative previews')
  const mapRef=useRef<HTMLDivElement>(null),fileRef=useRef<HTMLInputElement>(null),shellRef=useRef<HTMLDivElement>(null)
  const drag=useRef<null|{kind:string;startX:number;startY:number;value:number;pan:{x:number;y:number};region:typeof region}>(null)
  useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape'){setWelcome(false);setLayers(false)}};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[])
  useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),5000);return()=>clearTimeout(timer)},[notice])
  function start(e:ReactPointerEvent<HTMLElement>,kind:string,value=0){e.preventDefault();e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);drag.current={kind,startX:e.clientX,startY:e.clientY,value,pan:{...pan},region:{...region}}}
  function move(e:ReactPointerEvent<HTMLElement>){const d=drag.current;if(!d)return;const dx=e.clientX-d.startX,dy=e.clientY-d.startY;const box=mapRef.current?.getBoundingClientRect();
    const width=shellRef.current?.clientWidth||innerWidth
    if(d.kind==='left')setLeftWidth(clamp(d.value+dx,200,Math.min(470,width*.34)))
    if(d.kind==='right')setRightWidth(clamp(d.value-dx,300,Math.min(520,width*.4)))
    if(d.kind==='split'&&box)setSplit(clamp((e.clientX-box.left)/box.width*100,5,95))
    if(d.kind==='pan')setPan({x:clamp(d.pan.x+dx,-500,500),y:clamp(d.pan.y+dy,-400,400)})
    if(d.kind==='region'&&box)setRegion({...d.region,x:clamp(d.region.x+dx/box.width*100,0,100-d.region.w),y:clamp(d.region.y+dy/box.height*100,5,95-d.region.h)})
    if(d.kind==='corner'&&box)setRegion({...d.region,w:clamp(d.region.w+dx/box.width*100,12,98-d.region.x),h:clamp(d.region.h+dy/box.height*100,12,96-d.region.y)})
  }
  const end=()=>{drag.current=null}
  function openImagery(){setDraft(chosen);setImagery(true);setLeft(true);setRight(false)}
  async function inspect(file:File){setUploadInfo('Inspecting raster…');const data=new FormData();data.append('file',file);try{const res=await fetch('/api/raster/inspect',{method:'POST',body:data});const item=await res.json();if(!res.ok)throw Error(item.detail||'Inspection failed');setUploadInfo(`${file.name} · ${item.width} × ${item.height} px · ${item.bands} bands · ${item.crs}`)}catch(e){setUploadInfo(e instanceof Error?e.message:'Local API is unavailable')}}
  async function search(){setSearchInfo('Searching public catalogue…');try{const res=await fetch('/api/catalog/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({bbox:[86.4,25.8,87.2,26.5],date_from:from,date_to:to,max_cloud:cloud,sources:[...(optical?['sentinel-2-l2a']:[]),...(sar?['sentinel-1-grd']:[])]})});const data=await res.json();setSearchInfo(data.live?`Catalogue responded with ${data.scenes.length} records. Prepared preview scenes remain below.`:'Catalogue unavailable. Showing prepared preview scenes.')}catch{setSearchInfo('Local API unavailable. Prepared scenes remain available.')}}
  async function analyse(){setAsked(question.trim()||asked);setQuestion('');setBusy(true);setCalculation(null);try{const res=await fetch('/api/demo/analysis');if(!res.ok)throw Error('Local analysis API unavailable');setCalculation(await res.json());setNotice('Synthetic GeoTIFF calculation completed. See the separate GIS result below.')}catch(e){setNotice(e instanceof Error?e.message:'Analysis failed')}finally{setBusy(false)}}
  function exportReport(){const data={title:'SatQuery AI evidence brief',question:asked,scenes:chosen.map(id=>scenes.find(s=>s.id===id)),mode:'Prepared narrative with illustrative map',narrative:'Possible water expansion is illustrated east of the river corridor. This is not a validated flood observation.',syntheticGISCalculation:calculation,selectedRegion:region};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='satquery-evidence-brief.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('Evidence brief downloaded')}
  const style={'--rail':rail?'180px':'72px','--left':left?`${imagery?Math.max(leftWidth,400):leftWidth}px`:'0px','--right':right?`${rightWidth}px`:'0px'} as CSSProperties
  return <main className="aw" style={style}>
    <aside className={'aw-rail '+(rail?'expanded':'')}><button className="aw-logo" onClick={home} aria-label="Back to landing"><Mark/>{rail&&<b>SatQuery AI</b>}</button><nav>{[{Icon:Home,name:'Workspace',action:()=>{setImagery(false);setLeft(true)}},{Icon:Image,name:'Imagery',action:openImagery},{Icon:SquareDashedMousePointer,name:'Selected region',action:()=>{setSelected(v=>!v);setNotice('Drag the region to move it; drag its lower-right handle to resize.')}},{Icon:MessageSquare,name:'Results',action:()=>setRight(v=>!v)},{Icon:FileText,name:'Export report',action:exportReport},{Icon:HelpCircle,name:'Tutorial',action:()=>setWelcome(true)}].map(({Icon,name,action},i)=><button key={name} title={name} aria-label={name} className={i===0?'current':''} onClick={action}><Icon/>{rail&&<span>{name}</span>}</button>)}</nav><button className="aw-rail-toggle" onClick={()=>setRail(v=>!v)} aria-label={rail?'Collapse navigation':'Expand navigation'}>{rail?<ChevronsLeft/>:<ChevronsRight/>}{rail&&'Collapse'}</button></aside>
    <header className="aw-header"><div><b>Flood assessment · Supaul</b><span><Cloud size={16}/> Local session</span></div><div className="aw-header-actions"><button onClick={()=>setLeft(v=>!v)} aria-label={left?'Hide scenes':'Show scenes'} title="Toggle scenes"><Layers size={17}/><span>Scenes</span></button><button onClick={()=>setRight(v=>!v)} aria-label={right?'Hide results':'Show results'} title="Toggle results"><MessageSquare size={17}/><span>Results</span></button><span className="aw-avatar">DK</span></div></header>
    <div className="aw-shell" ref={shellRef}>
      {left&&<aside className={'aw-scenes '+(imagery?'aw-imagery':'')}>
        <div className="aw-panel-heading"><h2>{imagery?'Add imagery':'Scenes'}</h2><button aria-label={imagery?'Close imagery':'Collapse scenes'} onClick={()=>imagery?setImagery(false):setLeft(false)}>{imagery?<X/>:<PanelLeftClose/>}</button></div>
        {!imagery?<><button className="aw-add" onClick={openImagery}><Plus/> Add imagery</button><div className="aw-scene-list">{scenes.filter(s=>chosen.includes(s.id)).map(s=><button key={s.id} className={'aw-scene '+(active===s.id?'selected':'')} onClick={()=>{setActive(s.id);setMask(s.id==='after')}}><div className="aw-scene-main"><div className={'aw-thumb '+s.id}/><div><b>{s.title}</b><span>{s.date}</span></div></div><span className="aw-pill">{s.kind}</span><div className="aw-valid"><Check/> Prepared scene <span>···</span></div></button>)}</div><p className="aw-scene-note">Illustrative scene previews. Original acquisitions are not loaded.</p></>:<>
          <div className="aw-tabs">{[['upload','Upload GeoTIFF'],['catalog','Search catalogue'],['prepared','Prepared scenes']].map(([id,label])=><button key={id} className={tab===id?'selected':''} onClick={()=>setTab(id)}>{label}</button>)}</div>
          <div className="aw-imagery-scroll">{tab==='upload'?<><label className="aw-drop"><Upload/><b>Choose a GeoTIFF</b><span>Inspect bands, dimensions and CRS</span><input type="file" accept=".tif,.tiff" onChange={e=>e.target.files?.[0]&&inspect(e.target.files[0])}/></label>{uploadInfo&&<p className="aw-upload-info" role="status">{uploadInfo}</p>}</>:<>
          {tab==='catalog'&&<><label className="aw-field">Location or coordinates<div><Search size={17}/><input value={place} onChange={e=>setPlace(e.target.value)}/></div></label><p className="aw-small">Prototype search bounds: Supaul district. Place text is a session label.</p><label className="aw-field">Date range</label><div className="aw-dates"><input aria-label="Start date" type="date" value={from} onChange={e=>setFrom(e.target.value)}/><span>–</span><input aria-label="End date" type="date" value={to} onChange={e=>setTo(e.target.value)}/></div><label className="aw-field">Source</label><div className="aw-sources"><label><input type="checkbox" checked={optical} onChange={e=>setOptical(e.target.checked)}/> Optical</label><label><input type="checkbox" checked={sar} onChange={e=>setSar(e.target.checked)}/> SAR</label></div><label className="aw-field">Cloud cover</label><div className="aw-cloud"><Cloud/><input aria-label="Maximum cloud cover" type="range" value={cloud} onChange={e=>setCloud(Number(e.target.value))}/><span>≤ {cloud}%</span></div><button className="aw-search-submit" disabled={!optical&&!sar} onClick={search}><Search size={16}/> Search public catalogue</button></>}
          <div className="aw-available"><b>Available scenes</b><span>3 previews</span></div><p className="aw-small" role="status">{tab==='prepared'?'Prepared demonstration scenes':searchInfo}</p>{scenes.map(s=><button className={'aw-catalog-scene '+(draft.includes(s.id)?'selected':'')} key={s.id} onClick={()=>setDraft(v=>v.includes(s.id)?v.filter(id=>id!==s.id):[...v,s.id])}><div className={'aw-thumb '+s.id}/><div><b>{s.kind==='SAR'?'Sentinel-1':'Sentinel-2'}</b><span>{s.date}</span><small>Cloud cover: {s.cloud===null?'N/A':s.cloud+'%'}</small></div><span>{s.kind}<small>10 m</small></span><i>{draft.includes(s.id)&&<Check size={12}/>}</i></button>)}</>}
          </div><div className="aw-imagery-footer"><button onClick={()=>setImagery(false)}><ArrowLeft/> Back</button><button className="aw-primary" disabled={!draft.length} onClick={()=>{setChosen(draft);setImagery(false)}}>Add selected scenes <ArrowRight/></button></div>
        </>}
      </aside>}
      {left&&<div className="aw-resizer aw-resizer-left" role="separator" aria-label="Resize scenes panel" aria-orientation="vertical" aria-valuenow={leftWidth} tabIndex={0} onKeyDown={e=>{if(e.key==='ArrowRight')setLeftWidth(v=>clamp(v+20,200,470));if(e.key==='ArrowLeft')setLeftWidth(v=>clamp(v-20,200,470))}} onPointerDown={e=>start(e,'left',leftWidth)} onPointerMove={move} onPointerUp={end} onPointerCancel={end}/>}
      <div className="aw-map" ref={mapRef}>
        <div className="aw-map-pan" onPointerDown={e=>start(e,'pan')} onPointerMove={move} onPointerUp={end} onPointerCancel={end} style={{transform:`translate(${pan.x}px,${pan.y}px) scale(${zoom})`}}><div className="aw-map-image"/><div className="aw-map-image aw-map-after" style={{clipPath:`inset(0 0 0 ${split}%)`}}/>
          {mask&&!imagery&&<svg className="aw-map-outline" viewBox="0 0 1000 800" preserveAspectRatio="none" aria-hidden="true"><path d="M490 210L509 194 524 209 522 229 543 241 539 262 557 274 548 291 572 312 591 306 610 327 638 333 644 354 669 368 662 386 692 404 682 425 708 440 702 457 728 475 722 497 751 517 742 540 767 559 752 574 777 602 759 613 735 591 715 597 699 579 675 577 659 554 638 548 628 525 608 516 606 492 579 477 570 451 545 435 549 409 528 390 532 365 512 344 521 321 502 300 510 277 493 258Z"/></svg>}
        </div>
        <div className="aw-map-top"><span>{imagery?place:'12 Aug 2023 (Before)'}</span>{!imagery&&<span>28 Aug 2023 (After)</span>}<button onClick={()=>setLayers(v=>!v)}><Layers/> Layers</button></div>
        {layers&&<div className="aw-layer-popover"><b>Map layers</b><label><input type="checkbox" checked={mask} onChange={e=>setMask(e.target.checked)}/> Illustrative change boundary</label><label><input type="checkbox" checked={selected} onChange={e=>setSelected(e.target.checked)}/> Selected region</label><small>Preview image · not a geospatial basemap</small></div>}
        {!imagery&&<div className="aw-divider" style={{left:`${split}%`}}><button aria-label="Drag image comparison divider" onPointerDown={e=>start(e,'split')} onPointerMove={move} onPointerUp={end} onPointerCancel={end} onKeyDown={e=>{if(e.key==='ArrowLeft')setSplit(v=>clamp(v-2,5,95));if(e.key==='ArrowRight')setSplit(v=>clamp(v+2,5,95))}}>◀ ▶</button></div>}
        {imagery&&<div className="aw-aoi" style={{left:`${region.x}%`,top:`${region.y}%`,width:`${region.w}%`,height:`${region.h}%`}} onPointerDown={e=>start(e,'region')} onPointerMove={move} onPointerUp={end} onPointerCancel={end}><span>Drag to move your area</span><i/><i/><i/><button aria-label="Resize selected area" onPointerDown={e=>start(e,'corner')} onPointerMove={move} onPointerUp={end} onPointerCancel={end}/></div>}
        {selected&&!imagery&&<div className="aw-region-tag"><MapPin/><span>Selected floodplain<small>Illustrative region</small></span></div>}
        {!left&&<button className="aw-reopen-left" aria-label="Show scenes" onClick={()=>setLeft(true)}><Layers/> Scenes</button>}{!right&&<button className="aw-reopen-right" aria-label="Show results" onClick={()=>setRight(true)}><MessageSquare/> Results</button>}
        <div className="aw-zoom"><button aria-label="Zoom in" onClick={()=>setZoom(v=>clamp(v+.25,1,3))}><Plus/></button><button aria-label="Zoom out" onClick={()=>setZoom(v=>clamp(v-.25,1,3))}><Minus/></button><button aria-label="Reset view" onClick={()=>{setZoom(1);setPan({x:0,y:0})}}><LocateFixed/></button></div><div className="aw-map-bottom"><b>↑<small>N</small></b><span>Illustrative imagery · {zoom.toFixed(2)}×</span><span>Drag map to pan</span></div>
      </div>
      {right&&<div className="aw-resizer aw-resizer-right" role="separator" aria-label="Resize results panel" aria-orientation="vertical" aria-valuenow={rightWidth} tabIndex={0} onKeyDown={e=>{if(e.key==='ArrowLeft')setRightWidth(v=>clamp(v+20,300,520));if(e.key==='ArrowRight')setRightWidth(v=>clamp(v-20,300,520))}} onPointerDown={e=>start(e,'right',rightWidth)} onPointerMove={move} onPointerUp={end} onPointerCancel={end}/>}
      {right&&<aside className="aw-results"><div className="aw-result-head"><Mark/><b>SATQUERY</b><button aria-label="Collapse results" onClick={()=>setRight(false)}><PanelRightClose/></button></div><div className="aw-result-scroll"><h2>{asked}</h2><div className="aw-answer-card"><p>Possible flood expansion is illustrated east of the main channel.</p><div><span><SquareDashedMousePointer/><small>Evidence status<b>Preview</b></small></span><span><Layers/><small>Scene pair<b>{chosen.length} selected</b></small></span></div></div><p className="aw-small">Prepared narrative · illustrative imagery. No flood extent or confidence is validated for this preview.</p><h3>Evidence</h3><div className="aw-evidence"><button onClick={()=>setMask(v=>!v)}><Layers/> {mask?'Hide':'Show'} boundary</button><button onClick={()=>{setActive('before');setSplit(95)}}><Image/> Before</button><button onClick={()=>{setActive('after');setSplit(5)}}><Image/> After</button></div><details className="aw-trace" open><summary>Analysis trace <ChevronDown/></summary><div>{(calculation?.trace||[{label:'Prepared scenes selected',detail:'Illustrative previews'},{label:'Region attached',detail:'Selected area context'},{label:'GIS calculation available',detail:'Run on bundled synthetic GeoTIFFs'}]).map(t=><p key={t.label}><Check/><span>{t.label}<small>{t.detail}</small></span></p>)}</div></details>{calculation&&<div className="aw-gis"><b>Synthetic GeoTIFF result</b><strong>{calculation.expandedAreaHa.toLocaleString()} ha</strong><span>New water in test rasters · +{calculation.changePercent}%</span><small>This measurement belongs to the synthetic test data, not the map illustration.</small></div>}</div><div className="aw-result-bottom">{selected&&<div className="aw-selected-chip"><MapPin/> Selected region<button aria-label="Clear selected region" onClick={()=>setSelected(false)}><X/></button></div>}<form onSubmit={e=>{e.preventDefault();analyse()}}><button type="button" aria-label="Attach GeoTIFF" onClick={()=>{openImagery();setTab('upload')}}><Paperclip/></button><input aria-label="Ask about this area" placeholder="Ask about this area" value={question} onChange={e=>setQuestion(e.target.value)}/><button aria-label="Run analysis" disabled={busy}><Send/></button></form><button className="aw-run-note" disabled={busy} onClick={analyse}>{busy?'Calculating…':'Run synthetic GIS demonstration'}</button><button className="aw-primary aw-export" onClick={exportReport}><FileText/> Export report <Download/></button></div></aside>}
    </div>
    {notice&&<div className="aw-toast" role="status">{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice('')}><X size={15}/></button></div>}
    {welcome&&<div className="aw-welcome-backdrop"><section className="aw-welcome" role="dialog" aria-modal="true" aria-label="Choose your investigation"><div className="aw-welcome-brand"><Mark/><b>SatQuery AI</b><button aria-label="Close tutorial" onClick={()=>setWelcome(false)}><X/></button></div><h1>What do you need to investigate?</h1><div className="aw-task-options">{[{Icon:Image,title:'Understand one image',copy:'Ask questions and describe visible features'},{Icon:MapPin,title:'Locate something',copy:'Highlight a region mentioned in your question'},{Icon:Clock3,title:'Compare two dates',copy:'Find, describe and measure change'},{Icon:Layers,title:'Combine optical + SAR',copy:'Cross-check complementary evidence'}].map(({Icon,title,copy},i)=><button className={task===i?'selected':''} key={title} onClick={()=>setTask(i)}><Icon/><span><b>{title}</b><small>{copy}</small></span>{task===i&&<i/>}</button>)}</div><button className="aw-prepared" onClick={()=>{setWelcome(false);setImagery(false)}}><FileText/> Try a prepared flood scenario <ArrowRight/></button><div className="aw-welcome-footer"><span>Choose a workflow</span><button onClick={()=>setWelcome(false)}>Skip tutorial</button><button className="aw-primary" onClick={()=>{setWelcome(false);if(task!==2)setNotice('This build demonstrates temporal analysis. Other model workflows are planned.');openImagery()}}>Continue <ArrowRight/></button></div></section></div>}
  </main>
}
